package com.mycompany.ivr.Vista;

import com.mycompany.ivr.Clases.Llamada;
import com.mycompany.ivr.Controlador.ControladorConsultarEncuesta;
import java.util.Date;
import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

public class PantallaConsultarEncuesta extends javax.swing.JFrame {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("persistence-unit");
        EntityManager em = emf.createEntityManager();

        ControladorConsultarEncuesta gestor = new ControladorConsultarEncuesta(em, this);

        public ControladorConsultarEncuesta getGestor() {
                return gestor;
        }

        public void setGestor(ControladorConsultarEncuesta gestor) {
                this.gestor = gestor;
        }

        public PantallaConsultarEncuesta() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        // @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                lblFechaInicio = new javax.swing.JLabel();
                lblFechaFin = new javax.swing.JLabel();
                jdcFechaInicio = new com.toedter.calendar.JDateChooser();
                jdcFechaFin = new com.toedter.calendar.JDateChooser();
                jPanel2 = new javax.swing.JPanel();
                jspLlamadas = new javax.swing.JScrollPane();
                tblLlamadas = new javax.swing.JTable();
                jPanel3 = new javax.swing.JPanel();
                lblEncuestaRealizada = new javax.swing.JLabel();
                lblDescripcionEncuesta = new javax.swing.JLabel();
                jPanel4 = new javax.swing.JPanel();
                jspEncuestas = new javax.swing.JScrollPane();
                tblEncuestas = new javax.swing.JTable();
                jPanel5 = new javax.swing.JPanel();
                btnGenerarCSV = new javax.swing.JButton();
                btnImprimir = new javax.swing.JButton();
                btnCancelar = new javax.swing.JButton();
                btnFiltrar = new javax.swing.JButton();
                lblCliente = new javax.swing.JLabel();
                lblEstadoLlamada = new javax.swing.JLabel();
                lblDuracionLlamada = new javax.swing.JLabel();
                jMenuBar1 = new javax.swing.JMenuBar();
                jMenu1 = new javax.swing.JMenu();
                btnConsultarEncuesta = new javax.swing.JMenuItem();
                jMenuItem2 = new javax.swing.JMenuItem();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setPreferredSize(new java.awt.Dimension(464, 345));

                lblFechaInicio.setText("Ingresar fecha de inicio:");
                lblFechaInicio.setEnabled(false);

                lblFechaFin.setText("Ingresar fecha de fin:");
                lblFechaFin.setEnabled(false);

                jdcFechaInicio.setEnabled(false);

                jdcFechaFin.setEnabled(false);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                .addComponent(jdcFechaFin,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(jdcFechaInicio,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE))
                                                                                                                .addGap(292, 292,
                                                                                                                                292))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(lblFechaInicio)
                                                                                                                .addComponent(lblFechaFin))
                                                                                                .addContainerGap(
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)))));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(lblFechaInicio)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jdcFechaInicio,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(lblFechaFin)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jdcFechaFin,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(7, 7, 7)));

                jspLlamadas.setEnabled(false);

                tblLlamadas.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {

                                },
                                new String[] {
                                                "Llamada"
                                }) {
                        Class[] types = new Class[] {
                                        java.lang.Object.class, java.lang.String.class, java.lang.Object.class,
                                        java.lang.Object.class
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types[columnIndex];
                        }
                });
                tblLlamadas.setEnabled(false);
                // tblLlamadas.setTableHeader(Llamada);
                tblLlamadas.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tomarSeleccionLlamadaConEncuesta(evt);
                        }
                });
                jspLlamadas.setViewportView(tblLlamadas);

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(jspLlamadas,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                600,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 6, Short.MAX_VALUE)));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jspLlamadas, javax.swing.GroupLayout.DEFAULT_SIZE, 205,
                                                                Short.MAX_VALUE));

                lblEncuestaRealizada.setEnabled(false);

                lblDescripcionEncuesta.setText("");
                lblDescripcionEncuesta.setEnabled(false);

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(lblEncuestaRealizada)
                                                                                .addComponent(lblDescripcionEncuesta))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(lblEncuestaRealizada)
                                                                .addGap(12, 12, 12)
                                                                .addComponent(lblDescripcionEncuesta)));

                jspEncuestas.setEnabled(false);

                tblEncuestas.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {

                                },
                                new String[] {
                                                "Pregunta", "DescripciónPregunta", "RespuestaSeleccionada"
                                }));
                tblEncuestas.setEnabled(false);
                jspEncuestas.setViewportView(tblEncuestas);

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jspEncuestas,
                                                                javax.swing.GroupLayout.Alignment.TRAILING));
                jPanel4Layout.setVerticalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout
                                                                .createSequentialGroup()
                                                                .addComponent(jspEncuestas,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                206, Short.MAX_VALUE)
                                                                .addContainerGap()));

                jPanel5.setPreferredSize(new java.awt.Dimension(824, 161));

                btnGenerarCSV.setText("Generar CSV");
                btnGenerarCSV.setActionCommand("Volver");
                btnGenerarCSV.setEnabled(false);
                btnGenerarCSV.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnGenerarCSVActionPerformed(evt);
                        }
                });

                btnImprimir.setText("Imprimir");
                btnImprimir.setActionCommand("Volver");
                btnImprimir.setEnabled(false);
                btnImprimir.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnImprimirActionPerformed(evt);
                        }
                });

                btnCancelar.setText("Cancelar");
                btnCancelar.setActionCommand("Volver");
                btnCancelar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCancelarActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(btnGenerarCSV)
                                                                .addGap(32, 32, 32)
                                                                .addComponent(btnImprimir)
                                                                .addGap(51, 51, 51)
                                                                .addComponent(btnCancelar)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel5Layout.setVerticalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout
                                                                .createSequentialGroup()
                                                                .addGap(0, 4, Short.MAX_VALUE)
                                                                .addGroup(jPanel5Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btnGenerarCSV)
                                                                                .addComponent(btnImprimir)
                                                                                .addComponent(btnCancelar))));

                btnFiltrar.setText("Filtrar");
                btnFiltrar.setActionCommand("Volver");
                btnFiltrar.setEnabled(false);
                btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnFiltrarActionPerformed(evt);
                        }
                });

                lblCliente.setText("");
                lblCliente.setEnabled(false);

                lblEstadoLlamada.setText("");
                lblEstadoLlamada.setEnabled(false);

                lblDuracionLlamada.setText("");
                lblDuracionLlamada.setEnabled(false);

                jMenu1.setText("Archivo");

                btnConsultarEncuesta.setText("Consultar Encuesta");
                jMenu1.add(btnConsultarEncuesta);

                jMenuItem2.setText("Salir");
                jMenu1.add(jMenuItem2);

                jMenuBar1.add(jMenu1);

                setJMenuBar(jMenuBar1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 606,
                                                                Short.MAX_VALUE)
                                                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 606,
                                                                Short.MAX_VALUE)
                                                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(btnFiltrar)
                                                                                .addComponent(lblCliente)
                                                                                .addComponent(lblEstadoLlamada)
                                                                                .addComponent(lblDuracionLlamada))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                105,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(1, 1, 1)
                                                                .addComponent(btnFiltrar)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(lblCliente)
                                                                .addGap(12, 12, 12)
                                                                .addComponent(lblEstadoLlamada)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(lblDuracionLlamada)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                93,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jPanel4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel5,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                29,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap()));

                lblCliente.getAccessibleContext().setAccessibleName("lblCliente");
                lblEstadoLlamada.getAccessibleContext().setAccessibleName("lblEstadoaLlamada");
                lblDuracionLlamada.getAccessibleContext().setAccessibleName("lblDuracion");

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnFiltrarActionPerformed
                long FI = tomarFechaInicio().getTime();
                long FF = tomarFechaFin().getTime();

                Date fechaInicio = new Date(FI);
                Date fechaFin = new Date(FF);

                this.getGestor().tomarPeriodo(fechaInicio, fechaFin);
                /**
                 * El método tomarPeriodo() tiene que llamar a buscarLlamadasConEncuesta()
                 * El método buscarLlamadasConEncuesta() tiene que:
                 * - agregar los métodos determinarFechaInicioLlamada(), que va a llamar a
                 * getFechaHoraInicio() de CambioEstado
                 * - llamar al método mostrarLlamadasConEncuestaParaSeleccion() de la pantalla
                 */

                // this.mostrarLlamadasConEncuestaParaSeleccion();
        }// GEN-LAST:event_btnFiltrarActionPerformed

        private void tomarSeleccionLlamadaConEncuesta(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tomarSeleccionLlamadaConEncuesta
                Llamada llamadaSeleccionada = tomarSeleccionLlamadaConEncuesta();
                this.getGestor().tomarSeleccionLlamadaConEncuesta(llamadaSeleccionada);
                /**
                 * El método tomarSeleccionLlamadaConEncuesta() del gestor tiene que llamar a
                 * obtenerDatosLlamada()
                 * Fijarse los nombres de los métodos en obtenerDatosLlamada() y llamar a
                 * obtenerDatosEncuesta()
                 * obtenerDatosEncuesta tiene que llamar a buscarEncuestaAsociada()
                 * buscarEncuestaAsociada() debe llamar a armarEncuesta()
                 * armarEncuesta() tiene que llamar a mostrarEncuesta() de la pantalla
                 */
                // this.mostrarEncuesta(); // PROVISORIO
        }// GEN-LAST:event_tomarSeleccionLlamadaConEncuesta

        private void btnGenerarCSVActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnGenerarCSVActionPerformed
                tomarOpcionSalida("CSV");
        }// GEN-LAST:event_btnGenerarCSVActionPerformed

        private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnImprimirActionPerformed
                tomarOpcionSalida("Imprimir");
        }// GEN-LAST:event_btnImprimirActionPerformed

        private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarActionPerformed
                System.exit(0);
        }// GEN-LAST:event_btnCancelarActionPerformed

        public void opcionConsultarEncuesta() {
                habilitarVentana();
        }

        public void habilitarVentana() {
                setVisible(true);
                // gestor.ConsultarEncuesta(); Agregar método en el gestor que simplemente llame
                // a habilitarFiltroPorPeriodo()
                Boolean habilitarFiltro = this.getGestor().opcionConsultarEncuesta();
                if (habilitarFiltro) {
                        this.habilitarFiltroPorPeriodo();
                }
        }

        public void habilitarFiltroPorPeriodo() {
                lblFechaInicio.setEnabled(true);
                lblFechaFin.setEnabled(true);
                jdcFechaInicio.setEnabled(true);
                jdcFechaFin.setEnabled(true);
                btnFiltrar.setEnabled(true);
        }

        public Date tomarFechaInicio() {
                return jdcFechaInicio.getDate();
        }

        public Date tomarFechaFin() {
                return jdcFechaFin.getDate();
        }

        public void mostrarLlamadasConEncuestaParaSeleccion() {
                jspLlamadas.setEnabled(true);
                tblLlamadas.setEnabled(true);

                DefaultTableModel model = (DefaultTableModel) tblLlamadas.getModel();
                model.setRowCount(0);
                List<Llamada> llamadas = this.getGestor().getListaLlamadas();
                if (llamadas.isEmpty()) {
                        lblDescripcionEncuesta.setText("NO SE ENCONTRARON LLAMADAS EN EL PERIÓDO ESTABLECIDO");
                        lblCliente.setText("");
                        lblEstadoLlamada.setText("");
                        lblDuracionLlamada.setText("");
                        btnGenerarCSV.setEnabled(false);
                        btnImprimir.setEnabled(false);
                        DefaultTableModel modelEncuesta = (DefaultTableModel) tblEncuestas.getModel();
                        modelEncuesta.setRowCount(0);
                } else {
                        lblDescripcionEncuesta.setText("");
                }
                Object rowData[] = new Object[1];
                for (int i = 0; i < llamadas.size(); i++) {
                        rowData[0] = "Llamada " + (i + 1);
                        model.addRow(rowData);
                }
        }

        public Llamada tomarSeleccionLlamadaConEncuesta() {
                int llamadaSeleccionada = tblLlamadas.getSelectedRow();
                return this.getGestor().getListaLlamadas().get(llamadaSeleccionada);
        }

        public void mostrarEncuesta() {
                lblEncuestaRealizada.setEnabled(true);
                lblDescripcionEncuesta.setEnabled(true);

                String descEncuesta = this.getGestor().getDescripcionEncuesta();
                String nombreCliente = this.getGestor().getNombreCliente();
                String estadoLlamada = this.getGestor().getUltimoEstadoLlamada();
                String duracionLlamada = this.getGestor().getDuracionLlamada();
                lblDescripcionEncuesta.setText("Descripción de encuesta: " + descEncuesta);
                lblCliente.setText("Cliente: " + nombreCliente);
                lblEstadoLlamada.setText("Estado actual: " + estadoLlamada);
                lblDuracionLlamada.setText("Duración: " + duracionLlamada);

                jspEncuestas.setEnabled(true);
                tblEncuestas.setEnabled(false);

                DefaultTableModel model = (DefaultTableModel) tblEncuestas.getModel();
                model.setRowCount(0);
                List<String> respuestas = this.getGestor().getRespuestas();
                List<String> descPreguntas = this.getGestor().getPreguntas();
                Object rowData[] = new Object[3];
                for (int i = 0; i < respuestas.size(); i++) {
                        String respuestaCompleta = respuestas.get(i);
                        String[] respuestaPartidaSinEspacioEnMemoria = respuestaCompleta.split("_");
                        String respuesta = respuestaPartidaSinEspacioEnMemoria[0];
                        String[] respuestaPartida = respuesta.split("-");
                        String respuestaCiente = respuestaPartida[0];
                        String respuestaSeleccionada = respuestaPartida[1];
                        rowData[0] = descPreguntas.get(i);
                        rowData[1] = respuestaCiente;
                        rowData[2] = respuestaSeleccionada;
                        model.addRow(rowData);
                }
        }

        public void mostrarOpcionesSalida() {
                btnGenerarCSV.setEnabled(true);
                btnImprimir.setEnabled(true);
        }

        public void tomarOpcionSalida(String salida) {
                this.getGestor().tomarSalida(salida);
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(PantallaConsultarEncuesta.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(PantallaConsultarEncuesta.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(PantallaConsultarEncuesta.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(PantallaConsultarEncuesta.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new PantallaConsultarEncuesta().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCancelar;
        private javax.swing.JMenuItem btnConsultarEncuesta;
        private javax.swing.JButton btnFiltrar;
        private javax.swing.JButton btnGenerarCSV;
        private javax.swing.JButton btnImprimir;
        private javax.swing.JMenu jMenu1;
        private javax.swing.JMenuBar jMenuBar1;
        private javax.swing.JMenuItem jMenuItem2;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private com.toedter.calendar.JDateChooser jdcFechaFin;
        private com.toedter.calendar.JDateChooser jdcFechaInicio;
        private javax.swing.JScrollPane jspEncuestas;
        private javax.swing.JScrollPane jspLlamadas;
        private javax.swing.JLabel lblDescripcionEncuesta;
        private javax.swing.JLabel lblCliente;
        private javax.swing.JLabel lblEstadoLlamada;
        private javax.swing.JLabel lblDuracionLlamada;
        private javax.swing.JLabel lblEncuestaRealizada;
        private javax.swing.JLabel lblFechaFin;
        private javax.swing.JLabel lblFechaInicio;
        private javax.swing.JTable tblEncuestas;
        private javax.swing.JTable tblLlamadas;
        // End of variables declaration//GEN-END:variables
}
